# Generated by Django 5.1.6 on 2025-02-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_mpesapayment_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='status',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Pendente')], max_length=20),
        ),
    ]
