# Generated by Django 5.1.6 on 2025-02-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
