# Generated by Django 5.1.6 on 2025-02-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_aula_video_file_alter_aula_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
